name: Deploy-odoc

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 5.0.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.x
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
#            janestreet-bleeding: https://ocaml.janestreet.com/opam-repository
#            janestreet-bleeding-external: https://github.com/janestreet/opam-repository.git#external-packages

      - run: opam install . --deps-only --with-doc
        shell: bash

      - run: opam depext --install odoc
        shell: bash

      - name: build-doc
        run: |
             make odoc
             touch _build/docs/.nojekyll
             touch _build/docs/sphinx/.nojekyll
             touch _build/docs/doc/.nojekyll

      - name: Build HTML
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
          build-command: "sphinx-build -b html doc _build/docs/sphinx"

      - name: Deploy odoc to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: _build/docs
