name: deploy-doc

on:
  push:
    branches:
      - main

jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use OCaml 5.0.x
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: 5.0.x
          dune-cache: true
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
#            janestreet-bleeding: https://ocaml.janestreet.com/opam-repository
#            janestreet-bleeding-external: https://github.com/janestreet/opam-repository.git#external-packages

      - run: opam install . --deps-only --with-doc
        shell: bash

      - run: opam depext --install odoc
        shell: bash

      - name: Prepare doc directory
        run: |
             mkdir -p _build/docs
             mkdir -p _build/docs/odoc
             mkdir -p _build/docs/sphinx

      - name: Build odoc
        run: |
             make odoc

      - name: Build sphinx-doc
        uses: ammaraskar/sphinx-action@master
        with:
          docs-folder: "doc/"
          build-command: "sphinx-build . ../_build/docs/sphinx"

      - name: More doc files
        run: |
               touch _build/docs/.nojekyll
               touch _build/docs/sphinx/.nojekyll
               touch _build/docs/odoc/.nojekyll

      - name: Deploy doc to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ github.token }}
          publish_dir: _build/docs
